default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: db
  pool: 5

development:
  <<: *default
  database: desafio_smartfit2_development

test:
  <<: *default
  database: desafio_smartfit2_test

production:
  <<: *default
  database: desafio_smartfit2_production
